"""Phase order and tool membership shared by CLI and Desktop."""
PHASES = [{'id': '01_osint',
  'name': 'OSINT & reconnaissance passive',
  'tools': ['whois', 'dig', 'subfinder', 'amass', 'dnsrecon', 'theharvester', 'shodan']},
 {'id': '02_recon', 'name': 'Scan réseau', 'tools': ['nmap', 'rustscan', 'masscan', 'naabu']},
 {'id': '03_web_enum',
  'name': 'Énumération Web',
  'tools': ['gobuster', 'ffuf', 'httpx', 'wafw00f', 'whatweb', 'katana', 'gau', 'waybackurls']},
 {'id': '04_vulnscan',
  'name': 'Vulnérabilités',
  'tools': ['nikto', 'nuclei', 'wpscan', 'testssl.sh', 'sslscan']},
 {'id': '05_exploitation',
  'name': 'Exploitation',
  'tools': ['sqlmap', 'xsstrike', 'dalfox', 'msfconsole', 'msfvenom']},
 {'id': '06_postexploit',
  'name': 'Post-exploitation & privilèges',
  'tools': ['linpeas.sh',
            'winpeas',
            'secretsdump.py',
            'psexec.py',
            'GetUserSPNs.py',
            'crackmapexec',
            'bloodhound-python']},
 {'id': '07_passwords', 'name': 'Mots de passe', 'tools': ['hashcat', 'john', 'hydra']},
 {'id': '08_windows',
  'name': 'Windows / Active Directory',
  'tools': ['secretsdump.py', 'psexec.py', 'GetUserSPNs.py', 'crackmapexec', 'bloodhound-python']},
 {'id': '09_wireless',
  'name': 'Wi-Fi',
  'tools': ['airmon-ng', 'airodump-ng', 'aircrack-ng', 'reaver', 'wifite']},
 {'id': '10_network',
  'name': 'Réseau & MITM',
  'tools': ['bettercap', 'ettercap', 'tcpdump', 'responder']}]
